{{- if .Values.webhook.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.webhook.host }}
      http:
        paths:
          - path: /{{ .Values.webhook.path }}/{{ .Values.webhook.token }}/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 8080
{{- end }}
